# Generated by Django 2.0.2 on 2018-02-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.CharField(max_length=50, verbose_name='Compound')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyChar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=50, verbose_name='Textual property name')),
                ('propertyValue', models.CharField(max_length=50, verbose_name='Textual property value')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Material')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFloat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=50, verbose_name='Numerical property name')),
                ('propertyValue', models.FloatField(verbose_name='Numerical property value')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Material')),
            ],
        ),
    ]
