# Generated by Django 2.0.2 on 2018-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_formula', models.CharField(max_length=50, verbose_name='chemical formula')),
                ('property1_name', models.CharField(max_length=50, verbose_name='Property 1 name')),
                ('property1_value', models.FloatField(verbose_name='Property 1 value')),
                ('property2_name', models.CharField(max_length=50, verbose_name='Property 2 name')),
                ('property2_value', models.FloatField(verbose_name='Property 2 value')),
            ],
        ),
    ]
