# Generated by Django 2.0.3 on 2018-03-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.CharField(max_length=100, verbose_name='Compound')),
                ('elements', models.CharField(blank=True, max_length=100, verbose_name='Elements')),
                ('periods', models.CharField(blank=True, max_length=100, verbose_name='Periods')),
                ('groups', models.CharField(blank=True, max_length=100, verbose_name='Groups, CAS')),
                ('csv', models.CharField(blank=True, max_length=300, verbose_name='CSV')),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100, verbose_name='Property name')),
                ('propertyValue', models.CharField(max_length=100, verbose_name='Property value')),
                ('propertyValueFloat', models.FloatField(blank=True, default=None, null=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='data.Material')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
