# Generated by Django 2.0.2 on 2018-02-25 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100, verbose_name='Property name')),
                ('propertyValue', models.CharField(max_length=100, verbose_name='Property value')),
            ],
        ),
        migrations.RemoveField(
            model_name='propertychar',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='propertyfloat',
            name='compound',
        ),
        migrations.AlterField(
            model_name='material',
            name='compound',
            field=models.CharField(max_length=100, verbose_name='Compound'),
        ),
        migrations.DeleteModel(
            name='PropertyChar',
        ),
        migrations.DeleteModel(
            name='PropertyFloat',
        ),
        migrations.AddField(
            model_name='property',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='data.Material'),
        ),
    ]
