# Generated by Django 2.0.2 on 2018-02-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='property2_value',
            field=models.CharField(max_length=50, verbose_name='Property 2 value'),
        ),
    ]
